---
- name: "Install the required python packages for Azure"
  pip:
    name: "{{ item }}"
    state: "latest"
  become: "True"
  become_user: "root"
  with_items: "{{ azure_python_package_dependencies }}"
