---
- name: "Install tools required to fetch/unpack content from storage provider"
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "gzip"
  become: "True"
  become_user: "root"

- name: "Install dependencies for corresponding storage provider"
  include: "dependencies/{{ import_db_storage_provider }}.yml"
