---
- name: "Make sure temp folder exists"
  file:
    path: "{{ import_db_tmp_path }}"
    state: "directory"

- name: "Download the copy of the DB snapshot from the storage provider"
  include: "download-from/{{ import_db_storage_provider }}.yml"

# Note: Ansible does not support plain .gz files as part of its "unarchive" module, as they are not strictly speaking
# archives. See
#   - https://github.com/ansible/ansible-modules-extras/pull/1301
#   - https://github.com/ansible/ansible-modules-core/issues/1035
- name: "Unpack the DB"
  command: "gzip -d {{ import_db_tmp_path }}/db_dump.sql.gz"
  args:
    creates: "{{ import_db_tmp_path }}/db_dump.sql"
  when: "import_db_downloaded_archive.changed"

- name: "Delete the old database"
  mysql_db:
    name: "{{ import_db_database_name }}"
    state: "absent"
    login_password: "{{ import_db_root_password }}"
    login_user: "root"
  when: "import_db_downloaded_archive.changed"

- name: "Restore the database"
  mysql_db:
    name: "{{ import_db_database_name }}"
    state: "import"
    target: "{{ import_db_tmp_path }}/db_dump.sql"
    login_password: "{{ import_db_root_password }}"
    login_user: "root"

- name: "Clean up the db from /tmp"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ import_db_tmp_path }}/db_dump.sql"
    - "{{ import_db_tmp_path }}/db_dump.sql.gz"
    - "{{ import_db_tmp_path }}"
