---
- name: "Execute sql query"
  command: >
      mysql --user=root --password={{ import_db_root_password }}" {{ import_db_database_name }}"
      --execute="{{ import_db_post_import_sql_query.query }}"
